[build]
  base = ""
  command = "npm install && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_PUBLIC_RUNTIME = "netlify"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.x"
  NEXT_PUBLIC_SITE_URL = "https://cybernexacademy.netlify.app"
  NPM_VERSION = "9.x"
  CI = "true"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["@supabase/supabase-js"] 